[package]
name = "things-i-cant-afford"
version = "0.1.0"
authors = ["James Holby <jamesdholby@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
juniper = "0.11.1"
juniper_rocket = "0.2.0"
rocket = "0.4.0"

[dev-dependencies]
cargo-watch = "7.0.8"
