[package]
name = "server"
version = "0.1.0"
authors = ["James Holby <jamesdholby@gmail.com>"]
edition = "2018"

[dependencies]
juniper = "0.11.1"
rocket = "0.4.0"

[dev-dependencies]
cargo-watch = "7.0.8"
